services:
  app:
    build: .
    env_file:
      - .env
    command: ["python", "-m", "insert_package_name.main"]
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
      - ./logs:/app/logs

  scheduler:
    build: .
    env_file:
      - .env
    command: ["python", "-m", "insert_package_name.scheduler_main"]
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
      - ./logs:/app/logs
